platform :ios, "11.0"
#source 'git@github.com:OCdes/JTVoiceConvertSpecRepo.git'
#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'JTChat_Example' do
  pod 'JTChat', :path => '../'

end