platform :ios, "10.0"
source 'git@github.com:OCdes/JTVoiceConvertSpecRepo.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'JTChat_Example' do
  pod 'JTChat', :path => '../'

  #target 'JTChat_Tests' do
    #inherit! :search_paths

    #pod 'Quick'
   # pod 'Nimble'
   # pod 'FBSnapshotTestCase' 
    #pod 'Nimble-Snapshots' 
  #end
end
