platform :ios, "11.0"
#source 'git@github.com:OCdes/JTVoiceConvertSpecRepo.git'
#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'JTChat_Example' do
  pod 'JTChat', :path => '../'

  #target 'JTChat_Tests' do
    #inherit! :search_paths

    #pod 'Quick'
   # pod 'Nimble'
   # pod 'FBSnapshotTestCase' 
    #pod 'Nimble-Snapshots' 
  #end
end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end
  end
end